services:
  - type: web
    name: resume-analyzer
    runtime: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: your-secure-password
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

